### This file uses docker-compose
### There is a different file voting-app-swarm-mode.yml for running voting app in swarm mode with services

version: "2.1"
services:

  vote:
    image: dockersamples/examplevotingapp_vote:before
    networks:
      - frontend
    ports:
      - "8085:80"


  redis:
    image: redis:3.2
    networks:
      - frontend


  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - frontend
      - backend



  db:
    image: postgres:9.4
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    networks:
      - backend

  result:
    image: dockersamples/examplevotingapp_result:before
    networks:
      - backend
    ports:
      - "5001:80"

volumes:
  dbdata:

networks:
  backend:
  frontend:
