version: "2.1"
services:

   drupal:
     image: drupal
     networks:
       backend:
         aliases:
           - drupal
       frontend:
         aliases:
           - drupal
     ports:
       - "8080:80"
     depends_on:
       - postgres


   postgres:
     build : .
     image: postgres-custom
     networks:
       backend:
         aliases:
           - postgres_db
volumes:
   pgdata_vol:

networks:
   backend:
   frontend:
